
from datetime import timedelta, timezone, date, time, datetime

print(timedelta(days=7, hours=17, minutes=30))
# print(datetime.timezone(datetime.timedelta(hours=9)))
print(date(2022, 9, 19))

print('---------------------------------------------------')
today = date(2022,9,19)
print(today.year)
print(today.month)
print(today.day)
print(date.today())
print('------------------------------------------------')
print(time(13,42,35))
print(time.fromisoformat('13:42:35.458+09:00'))
t = time(13,42,35,458000, tzinfo=timezone(timedelta(hours=9)))
print(t.isoformat())
print(t.hour)
print(t.minute)
print(t.second)
print(t.microsecond)
print(t.replace(hour=14))
print('------------------------------------------------')
dt = datetime(2020,7,18,13,26,23)
d = date(2020,7,18)
t = time(13,26,23)
print(dt.combine(d,t))
print(datetime.now())
