# from time import localtime, time
#
# tm = localtime(time())
# print('year:',tm.tm_year)
# print('month:',tm.tm_mon)
# print('day:',tm.tm_mday)
# print('hour:',tm.tm_hour)
# print('minute:',tm.tm_min)
# print('second:',tm.tm_sec)
# print(tm)

import time
tm = time.localtime(time.time())
secs = time.time()
print('------------------------------------------------')
print(secs)
print('------------------------------------------------')
print('year:',tm.tm_year)
print('month:',tm.tm_mon)
print('day:',tm.tm_mday)
print('hour:',tm.tm_hour)
print('minute:',tm.tm_min)
print('second:',tm.tm_sec)
print('------------------------------------------------')
print(tm)
print('------------------------------------------------')
tm1 = time.localtime(secs)
string = time.strftime('%Y-%m-%d %I:%M:%S %p', tm1)
print(string)
print('------------------------------------------------')
string1 = time.ctime(secs)
print(string1)
print('------------------------------------------------')
print('before')
time.sleep(3)
print('after')